/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthImport } from './routes/_auth'
import { Route as AnonymousImport } from './routes/_anonymous'
import { Route as AuthStatisticsImport } from './routes/_auth/statistics'
import { Route as AuthApiImport } from './routes/_auth/api'
import { Route as AnonymousSignImport } from './routes/_anonymous/sign'
import { Route as AuthUsersIndexImport } from './routes/_auth/users/index'
import { Route as AuthRoomsIndexImport } from './routes/_auth/rooms/index'
import { Route as AuthHotelsIndexImport } from './routes/_auth/hotels/index'
import { Route as AuthBookingsIndexImport } from './routes/_auth/bookings/index'
import { Route as AuthUsersCreateImport } from './routes/_auth/users/create'
import { Route as AuthStatisticsRegistrationsImport } from './routes/_auth/statistics/registrations'
import { Route as AuthStatisticsLoginsImport } from './routes/_auth/statistics/logins'
import { Route as AuthStatisticsBookingsImport } from './routes/_auth/statistics/bookings'
import { Route as AuthRoomsCreateImport } from './routes/_auth/rooms/create'
import { Route as AuthRoomsBookImport } from './routes/_auth/rooms/book'
import { Route as AuthHotelsRateImport } from './routes/_auth/hotels/rate'
import { Route as AuthHotelsCreateImport } from './routes/_auth/hotels/create'
import { Route as AuthBookingsCreateImport } from './routes/_auth/bookings/create'
import { Route as AuthUsersEditIdImport } from './routes/_auth/users/edit.$id'
import { Route as AuthRoomsEditIdImport } from './routes/_auth/rooms/edit.$id'
import { Route as AuthHotelsEditIdImport } from './routes/_auth/hotels/edit.$id'
import { Route as AuthUsersProfileEditIdImport } from './routes/_auth/users/profile.edit.$id'

// Create Virtual Routes

const AnonymousIndexLazyImport = createFileRoute('/_anonymous/')()

// Create/Update Routes

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const AnonymousRoute = AnonymousImport.update({
  id: '/_anonymous',
  getParentRoute: () => rootRoute,
} as any)

const AnonymousIndexLazyRoute = AnonymousIndexLazyImport.update({
  path: '/',
  getParentRoute: () => AnonymousRoute,
} as any).lazy(() =>
  import('./routes/_anonymous/index.lazy').then((d) => d.Route),
)

const AuthStatisticsRoute = AuthStatisticsImport.update({
  path: '/statistics',
  getParentRoute: () => AuthRoute,
} as any)

const AuthApiRoute = AuthApiImport.update({
  path: '/api',
  getParentRoute: () => AuthRoute,
} as any)

const AnonymousSignRoute = AnonymousSignImport.update({
  path: '/sign',
  getParentRoute: () => AnonymousRoute,
} as any)

const AuthUsersIndexRoute = AuthUsersIndexImport.update({
  path: '/users/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthRoomsIndexRoute = AuthRoomsIndexImport.update({
  path: '/rooms/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthHotelsIndexRoute = AuthHotelsIndexImport.update({
  path: '/hotels/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthBookingsIndexRoute = AuthBookingsIndexImport.update({
  path: '/bookings/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthUsersCreateRoute = AuthUsersCreateImport.update({
  path: '/users/create',
  getParentRoute: () => AuthRoute,
} as any)

const AuthStatisticsRegistrationsRoute =
  AuthStatisticsRegistrationsImport.update({
    path: '/registrations',
    getParentRoute: () => AuthStatisticsRoute,
  } as any)

const AuthStatisticsLoginsRoute = AuthStatisticsLoginsImport.update({
  path: '/logins',
  getParentRoute: () => AuthStatisticsRoute,
} as any)

const AuthStatisticsBookingsRoute = AuthStatisticsBookingsImport.update({
  path: '/bookings',
  getParentRoute: () => AuthStatisticsRoute,
} as any)

const AuthRoomsCreateRoute = AuthRoomsCreateImport.update({
  path: '/rooms/create',
  getParentRoute: () => AuthRoute,
} as any)

const AuthRoomsBookRoute = AuthRoomsBookImport.update({
  path: '/rooms/book',
  getParentRoute: () => AuthRoute,
} as any)

const AuthHotelsRateRoute = AuthHotelsRateImport.update({
  path: '/hotels/rate',
  getParentRoute: () => AuthRoute,
} as any)

const AuthHotelsCreateRoute = AuthHotelsCreateImport.update({
  path: '/hotels/create',
  getParentRoute: () => AuthRoute,
} as any)

const AuthBookingsCreateRoute = AuthBookingsCreateImport.update({
  path: '/bookings/create',
  getParentRoute: () => AuthRoute,
} as any)

const AuthUsersEditIdRoute = AuthUsersEditIdImport.update({
  path: '/users/edit/$id',
  getParentRoute: () => AuthRoute,
} as any)

const AuthRoomsEditIdRoute = AuthRoomsEditIdImport.update({
  path: '/rooms/edit/$id',
  getParentRoute: () => AuthRoute,
} as any)

const AuthHotelsEditIdRoute = AuthHotelsEditIdImport.update({
  path: '/hotels/edit/$id',
  getParentRoute: () => AuthRoute,
} as any)

const AuthUsersProfileEditIdRoute = AuthUsersProfileEditIdImport.update({
  path: '/users/profile/edit/$id',
  getParentRoute: () => AuthRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_anonymous': {
      id: '/_anonymous'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AnonymousImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_anonymous/sign': {
      id: '/_anonymous/sign'
      path: '/sign'
      fullPath: '/sign'
      preLoaderRoute: typeof AnonymousSignImport
      parentRoute: typeof AnonymousImport
    }
    '/_auth/api': {
      id: '/_auth/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof AuthApiImport
      parentRoute: typeof AuthImport
    }
    '/_auth/statistics': {
      id: '/_auth/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof AuthStatisticsImport
      parentRoute: typeof AuthImport
    }
    '/_anonymous/': {
      id: '/_anonymous/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AnonymousIndexLazyImport
      parentRoute: typeof AnonymousImport
    }
    '/_auth/bookings/create': {
      id: '/_auth/bookings/create'
      path: '/bookings/create'
      fullPath: '/bookings/create'
      preLoaderRoute: typeof AuthBookingsCreateImport
      parentRoute: typeof AuthImport
    }
    '/_auth/hotels/create': {
      id: '/_auth/hotels/create'
      path: '/hotels/create'
      fullPath: '/hotels/create'
      preLoaderRoute: typeof AuthHotelsCreateImport
      parentRoute: typeof AuthImport
    }
    '/_auth/hotels/rate': {
      id: '/_auth/hotels/rate'
      path: '/hotels/rate'
      fullPath: '/hotels/rate'
      preLoaderRoute: typeof AuthHotelsRateImport
      parentRoute: typeof AuthImport
    }
    '/_auth/rooms/book': {
      id: '/_auth/rooms/book'
      path: '/rooms/book'
      fullPath: '/rooms/book'
      preLoaderRoute: typeof AuthRoomsBookImport
      parentRoute: typeof AuthImport
    }
    '/_auth/rooms/create': {
      id: '/_auth/rooms/create'
      path: '/rooms/create'
      fullPath: '/rooms/create'
      preLoaderRoute: typeof AuthRoomsCreateImport
      parentRoute: typeof AuthImport
    }
    '/_auth/statistics/bookings': {
      id: '/_auth/statistics/bookings'
      path: '/bookings'
      fullPath: '/statistics/bookings'
      preLoaderRoute: typeof AuthStatisticsBookingsImport
      parentRoute: typeof AuthStatisticsImport
    }
    '/_auth/statistics/logins': {
      id: '/_auth/statistics/logins'
      path: '/logins'
      fullPath: '/statistics/logins'
      preLoaderRoute: typeof AuthStatisticsLoginsImport
      parentRoute: typeof AuthStatisticsImport
    }
    '/_auth/statistics/registrations': {
      id: '/_auth/statistics/registrations'
      path: '/registrations'
      fullPath: '/statistics/registrations'
      preLoaderRoute: typeof AuthStatisticsRegistrationsImport
      parentRoute: typeof AuthStatisticsImport
    }
    '/_auth/users/create': {
      id: '/_auth/users/create'
      path: '/users/create'
      fullPath: '/users/create'
      preLoaderRoute: typeof AuthUsersCreateImport
      parentRoute: typeof AuthImport
    }
    '/_auth/bookings/': {
      id: '/_auth/bookings/'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof AuthBookingsIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/hotels/': {
      id: '/_auth/hotels/'
      path: '/hotels'
      fullPath: '/hotels'
      preLoaderRoute: typeof AuthHotelsIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/rooms/': {
      id: '/_auth/rooms/'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof AuthRoomsIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/users/': {
      id: '/_auth/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthUsersIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/hotels/edit/$id': {
      id: '/_auth/hotels/edit/$id'
      path: '/hotels/edit/$id'
      fullPath: '/hotels/edit/$id'
      preLoaderRoute: typeof AuthHotelsEditIdImport
      parentRoute: typeof AuthImport
    }
    '/_auth/rooms/edit/$id': {
      id: '/_auth/rooms/edit/$id'
      path: '/rooms/edit/$id'
      fullPath: '/rooms/edit/$id'
      preLoaderRoute: typeof AuthRoomsEditIdImport
      parentRoute: typeof AuthImport
    }
    '/_auth/users/edit/$id': {
      id: '/_auth/users/edit/$id'
      path: '/users/edit/$id'
      fullPath: '/users/edit/$id'
      preLoaderRoute: typeof AuthUsersEditIdImport
      parentRoute: typeof AuthImport
    }
    '/_auth/users/profile/edit/$id': {
      id: '/_auth/users/profile/edit/$id'
      path: '/users/profile/edit/$id'
      fullPath: '/users/profile/edit/$id'
      preLoaderRoute: typeof AuthUsersProfileEditIdImport
      parentRoute: typeof AuthImport
    }
  }
}

// Create and export the route tree

interface AnonymousRouteChildren {
  AnonymousSignRoute: typeof AnonymousSignRoute
  AnonymousIndexLazyRoute: typeof AnonymousIndexLazyRoute
}

const AnonymousRouteChildren: AnonymousRouteChildren = {
  AnonymousSignRoute: AnonymousSignRoute,
  AnonymousIndexLazyRoute: AnonymousIndexLazyRoute,
}

const AnonymousRouteWithChildren = AnonymousRoute._addFileChildren(
  AnonymousRouteChildren,
)

interface AuthStatisticsRouteChildren {
  AuthStatisticsBookingsRoute: typeof AuthStatisticsBookingsRoute
  AuthStatisticsLoginsRoute: typeof AuthStatisticsLoginsRoute
  AuthStatisticsRegistrationsRoute: typeof AuthStatisticsRegistrationsRoute
}

const AuthStatisticsRouteChildren: AuthStatisticsRouteChildren = {
  AuthStatisticsBookingsRoute: AuthStatisticsBookingsRoute,
  AuthStatisticsLoginsRoute: AuthStatisticsLoginsRoute,
  AuthStatisticsRegistrationsRoute: AuthStatisticsRegistrationsRoute,
}

const AuthStatisticsRouteWithChildren = AuthStatisticsRoute._addFileChildren(
  AuthStatisticsRouteChildren,
)

interface AuthRouteChildren {
  AuthApiRoute: typeof AuthApiRoute
  AuthStatisticsRoute: typeof AuthStatisticsRouteWithChildren
  AuthBookingsCreateRoute: typeof AuthBookingsCreateRoute
  AuthHotelsCreateRoute: typeof AuthHotelsCreateRoute
  AuthHotelsRateRoute: typeof AuthHotelsRateRoute
  AuthRoomsBookRoute: typeof AuthRoomsBookRoute
  AuthRoomsCreateRoute: typeof AuthRoomsCreateRoute
  AuthUsersCreateRoute: typeof AuthUsersCreateRoute
  AuthBookingsIndexRoute: typeof AuthBookingsIndexRoute
  AuthHotelsIndexRoute: typeof AuthHotelsIndexRoute
  AuthRoomsIndexRoute: typeof AuthRoomsIndexRoute
  AuthUsersIndexRoute: typeof AuthUsersIndexRoute
  AuthHotelsEditIdRoute: typeof AuthHotelsEditIdRoute
  AuthRoomsEditIdRoute: typeof AuthRoomsEditIdRoute
  AuthUsersEditIdRoute: typeof AuthUsersEditIdRoute
  AuthUsersProfileEditIdRoute: typeof AuthUsersProfileEditIdRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthApiRoute: AuthApiRoute,
  AuthStatisticsRoute: AuthStatisticsRouteWithChildren,
  AuthBookingsCreateRoute: AuthBookingsCreateRoute,
  AuthHotelsCreateRoute: AuthHotelsCreateRoute,
  AuthHotelsRateRoute: AuthHotelsRateRoute,
  AuthRoomsBookRoute: AuthRoomsBookRoute,
  AuthRoomsCreateRoute: AuthRoomsCreateRoute,
  AuthUsersCreateRoute: AuthUsersCreateRoute,
  AuthBookingsIndexRoute: AuthBookingsIndexRoute,
  AuthHotelsIndexRoute: AuthHotelsIndexRoute,
  AuthRoomsIndexRoute: AuthRoomsIndexRoute,
  AuthUsersIndexRoute: AuthUsersIndexRoute,
  AuthHotelsEditIdRoute: AuthHotelsEditIdRoute,
  AuthRoomsEditIdRoute: AuthRoomsEditIdRoute,
  AuthUsersEditIdRoute: AuthUsersEditIdRoute,
  AuthUsersProfileEditIdRoute: AuthUsersProfileEditIdRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AuthRouteWithChildren
  '/sign': typeof AnonymousSignRoute
  '/api': typeof AuthApiRoute
  '/statistics': typeof AuthStatisticsRouteWithChildren
  '/': typeof AnonymousIndexLazyRoute
  '/bookings/create': typeof AuthBookingsCreateRoute
  '/hotels/create': typeof AuthHotelsCreateRoute
  '/hotels/rate': typeof AuthHotelsRateRoute
  '/rooms/book': typeof AuthRoomsBookRoute
  '/rooms/create': typeof AuthRoomsCreateRoute
  '/statistics/bookings': typeof AuthStatisticsBookingsRoute
  '/statistics/logins': typeof AuthStatisticsLoginsRoute
  '/statistics/registrations': typeof AuthStatisticsRegistrationsRoute
  '/users/create': typeof AuthUsersCreateRoute
  '/bookings': typeof AuthBookingsIndexRoute
  '/hotels': typeof AuthHotelsIndexRoute
  '/rooms': typeof AuthRoomsIndexRoute
  '/users': typeof AuthUsersIndexRoute
  '/hotels/edit/$id': typeof AuthHotelsEditIdRoute
  '/rooms/edit/$id': typeof AuthRoomsEditIdRoute
  '/users/edit/$id': typeof AuthUsersEditIdRoute
  '/users/profile/edit/$id': typeof AuthUsersProfileEditIdRoute
}

export interface FileRoutesByTo {
  '': typeof AuthRouteWithChildren
  '/sign': typeof AnonymousSignRoute
  '/api': typeof AuthApiRoute
  '/statistics': typeof AuthStatisticsRouteWithChildren
  '/': typeof AnonymousIndexLazyRoute
  '/bookings/create': typeof AuthBookingsCreateRoute
  '/hotels/create': typeof AuthHotelsCreateRoute
  '/hotels/rate': typeof AuthHotelsRateRoute
  '/rooms/book': typeof AuthRoomsBookRoute
  '/rooms/create': typeof AuthRoomsCreateRoute
  '/statistics/bookings': typeof AuthStatisticsBookingsRoute
  '/statistics/logins': typeof AuthStatisticsLoginsRoute
  '/statistics/registrations': typeof AuthStatisticsRegistrationsRoute
  '/users/create': typeof AuthUsersCreateRoute
  '/bookings': typeof AuthBookingsIndexRoute
  '/hotels': typeof AuthHotelsIndexRoute
  '/rooms': typeof AuthRoomsIndexRoute
  '/users': typeof AuthUsersIndexRoute
  '/hotels/edit/$id': typeof AuthHotelsEditIdRoute
  '/rooms/edit/$id': typeof AuthRoomsEditIdRoute
  '/users/edit/$id': typeof AuthUsersEditIdRoute
  '/users/profile/edit/$id': typeof AuthUsersProfileEditIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_anonymous': typeof AnonymousRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_anonymous/sign': typeof AnonymousSignRoute
  '/_auth/api': typeof AuthApiRoute
  '/_auth/statistics': typeof AuthStatisticsRouteWithChildren
  '/_anonymous/': typeof AnonymousIndexLazyRoute
  '/_auth/bookings/create': typeof AuthBookingsCreateRoute
  '/_auth/hotels/create': typeof AuthHotelsCreateRoute
  '/_auth/hotels/rate': typeof AuthHotelsRateRoute
  '/_auth/rooms/book': typeof AuthRoomsBookRoute
  '/_auth/rooms/create': typeof AuthRoomsCreateRoute
  '/_auth/statistics/bookings': typeof AuthStatisticsBookingsRoute
  '/_auth/statistics/logins': typeof AuthStatisticsLoginsRoute
  '/_auth/statistics/registrations': typeof AuthStatisticsRegistrationsRoute
  '/_auth/users/create': typeof AuthUsersCreateRoute
  '/_auth/bookings/': typeof AuthBookingsIndexRoute
  '/_auth/hotels/': typeof AuthHotelsIndexRoute
  '/_auth/rooms/': typeof AuthRoomsIndexRoute
  '/_auth/users/': typeof AuthUsersIndexRoute
  '/_auth/hotels/edit/$id': typeof AuthHotelsEditIdRoute
  '/_auth/rooms/edit/$id': typeof AuthRoomsEditIdRoute
  '/_auth/users/edit/$id': typeof AuthUsersEditIdRoute
  '/_auth/users/profile/edit/$id': typeof AuthUsersProfileEditIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/sign'
    | '/api'
    | '/statistics'
    | '/'
    | '/bookings/create'
    | '/hotels/create'
    | '/hotels/rate'
    | '/rooms/book'
    | '/rooms/create'
    | '/statistics/bookings'
    | '/statistics/logins'
    | '/statistics/registrations'
    | '/users/create'
    | '/bookings'
    | '/hotels'
    | '/rooms'
    | '/users'
    | '/hotels/edit/$id'
    | '/rooms/edit/$id'
    | '/users/edit/$id'
    | '/users/profile/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/sign'
    | '/api'
    | '/statistics'
    | '/'
    | '/bookings/create'
    | '/hotels/create'
    | '/hotels/rate'
    | '/rooms/book'
    | '/rooms/create'
    | '/statistics/bookings'
    | '/statistics/logins'
    | '/statistics/registrations'
    | '/users/create'
    | '/bookings'
    | '/hotels'
    | '/rooms'
    | '/users'
    | '/hotels/edit/$id'
    | '/rooms/edit/$id'
    | '/users/edit/$id'
    | '/users/profile/edit/$id'
  id:
    | '__root__'
    | '/_anonymous'
    | '/_auth'
    | '/_anonymous/sign'
    | '/_auth/api'
    | '/_auth/statistics'
    | '/_anonymous/'
    | '/_auth/bookings/create'
    | '/_auth/hotels/create'
    | '/_auth/hotels/rate'
    | '/_auth/rooms/book'
    | '/_auth/rooms/create'
    | '/_auth/statistics/bookings'
    | '/_auth/statistics/logins'
    | '/_auth/statistics/registrations'
    | '/_auth/users/create'
    | '/_auth/bookings/'
    | '/_auth/hotels/'
    | '/_auth/rooms/'
    | '/_auth/users/'
    | '/_auth/hotels/edit/$id'
    | '/_auth/rooms/edit/$id'
    | '/_auth/users/edit/$id'
    | '/_auth/users/profile/edit/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AnonymousRoute: typeof AnonymousRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AnonymousRoute: AnonymousRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/_anonymous",
        "/_auth"
      ]
    },
    "/_anonymous": {
      "filePath": "_anonymous.jsx",
      "children": [
        "/_anonymous/sign",
        "/_anonymous/"
      ]
    },
    "/_auth": {
      "filePath": "_auth.jsx",
      "children": [
        "/_auth/api",
        "/_auth/statistics",
        "/_auth/bookings/create",
        "/_auth/hotels/create",
        "/_auth/hotels/rate",
        "/_auth/rooms/book",
        "/_auth/rooms/create",
        "/_auth/users/create",
        "/_auth/bookings/",
        "/_auth/hotels/",
        "/_auth/rooms/",
        "/_auth/users/",
        "/_auth/hotels/edit/$id",
        "/_auth/rooms/edit/$id",
        "/_auth/users/edit/$id",
        "/_auth/users/profile/edit/$id"
      ]
    },
    "/_anonymous/sign": {
      "filePath": "_anonymous/sign.jsx",
      "parent": "/_anonymous"
    },
    "/_auth/api": {
      "filePath": "_auth/api.jsx",
      "parent": "/_auth"
    },
    "/_auth/statistics": {
      "filePath": "_auth/statistics.jsx",
      "parent": "/_auth",
      "children": [
        "/_auth/statistics/bookings",
        "/_auth/statistics/logins",
        "/_auth/statistics/registrations"
      ]
    },
    "/_anonymous/": {
      "filePath": "_anonymous/index.lazy.jsx",
      "parent": "/_anonymous"
    },
    "/_auth/bookings/create": {
      "filePath": "_auth/bookings/create.jsx",
      "parent": "/_auth"
    },
    "/_auth/hotels/create": {
      "filePath": "_auth/hotels/create.jsx",
      "parent": "/_auth"
    },
    "/_auth/hotels/rate": {
      "filePath": "_auth/hotels/rate.jsx",
      "parent": "/_auth"
    },
    "/_auth/rooms/book": {
      "filePath": "_auth/rooms/book.jsx",
      "parent": "/_auth"
    },
    "/_auth/rooms/create": {
      "filePath": "_auth/rooms/create.jsx",
      "parent": "/_auth"
    },
    "/_auth/statistics/bookings": {
      "filePath": "_auth/statistics/bookings.jsx",
      "parent": "/_auth/statistics"
    },
    "/_auth/statistics/logins": {
      "filePath": "_auth/statistics/logins.jsx",
      "parent": "/_auth/statistics"
    },
    "/_auth/statistics/registrations": {
      "filePath": "_auth/statistics/registrations.jsx",
      "parent": "/_auth/statistics"
    },
    "/_auth/users/create": {
      "filePath": "_auth/users/create.jsx",
      "parent": "/_auth"
    },
    "/_auth/bookings/": {
      "filePath": "_auth/bookings/index.jsx",
      "parent": "/_auth"
    },
    "/_auth/hotels/": {
      "filePath": "_auth/hotels/index.jsx",
      "parent": "/_auth"
    },
    "/_auth/rooms/": {
      "filePath": "_auth/rooms/index.jsx",
      "parent": "/_auth"
    },
    "/_auth/users/": {
      "filePath": "_auth/users/index.jsx",
      "parent": "/_auth"
    },
    "/_auth/hotels/edit/$id": {
      "filePath": "_auth/hotels/edit.$id.jsx",
      "parent": "/_auth"
    },
    "/_auth/rooms/edit/$id": {
      "filePath": "_auth/rooms/edit.$id.jsx",
      "parent": "/_auth"
    },
    "/_auth/users/edit/$id": {
      "filePath": "_auth/users/edit.$id.jsx",
      "parent": "/_auth"
    },
    "/_auth/users/profile/edit/$id": {
      "filePath": "_auth/users/profile.edit.$id.jsx",
      "parent": "/_auth"
    }
  }
}
ROUTE_MANIFEST_END */
